# Generated by Django 4.0.4 on 2022-05-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_kr', models.CharField(blank=True, max_length=128, null=True)),
                ('company_en', models.CharField(blank=True, max_length=128, null=True)),
                ('company_ja', models.CharField(blank=True, max_length=128, null=True)),
                ('tag_ko', models.CharField(max_length=256)),
                ('tag_en', models.CharField(max_length=256)),
                ('tag_ja', models.CharField(max_length=256)),
            ],
        ),
    ]
