# Generated by Django 4.0.4 on 2022-05-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_kr', models.CharField(blank=True, max_length=128, null=True)),
                ('company_en', models.CharField(blank=True, max_length=128, null=True)),
                ('company_ja', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TagLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_nation', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'tag_lang',
            },
        ),
    ]
